server:
  port: 9091

spring:

  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9092
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/manager

        - id: admin-service
          uri: http://localhost:9093
          predicates:
            - Path=/admin/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/manager

        - id: manager-service
          uri: http://localhost:9094
          predicates:
            - Path=/manager/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/manager

        - id: personal-service
          uri: http://localhost:9095
          predicates:
            - Path=/personal/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/manager

        - id: visitor-service
          uri: http://localhost:9096
          predicates:
            - Path=/visitor/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/manager

        - id: company-service-company
          uri: http://localhost:9097
          predicates:
            - Path=/company/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/manager

        - id: company-service-shift
          uri: http://localhost:9097
          predicates:
            - Path=/shift/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/manager

        - id: company-service-communication
          uri: http://localhost:9097
          predicates:
            - Path=/communication/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/manager

        - id: company-service-break
          uri: http://localhost:9097
          predicates:
            - Path=/break/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/manager

        - id: payment-service
          uri: http://localhost:9098
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/manager

        - id: holiday-service
          uri: http://localhost:9101
          predicates:
            - Path=/holiday/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/manager



      default-filters:
        #       http://localhost/auth/findbyid/1
        #       (?<segment>.*)   ->    auth/findbyid/1
        #       $\{segment}      ->    http://localhost:9090/auth/findbyid/1
        - RewritePath=/?(?<segment>.*), /$\{segment}